### ISSUE TITLE
Using v-for inside Scroll-view

### ISSUE THREAD

**Issue by mapodev** [chrishurlburt/vue-scrollview#1]
Hey there,

I need help fixing my problem while using v-for inside the <Scroll-view>.

```
<Scroll-view>
   <template scope="inView">
      <coin v-for="(coin, key) in list" :visible="inView.key" :shortname="coin" key="key"></coin>
   </template>
</Scroll-view>
```

The parent Vue looks like this.

```
import Vue from 'vue'
import axios from 'axios'
import VueAxios from 'vue-axios'
import * as io from "socket.io-client";
import ScrollView from 'vue-scrollview';

Vue.use(VueAxios, axios);
Vue.use(ScrollView);

let home = new Vue({
    el: '#home-list',
    data: function () {
        return {
            coins: [],
            list: []
        };
    },

...

```

and the coin Component looks like this:

```
 import Vue from 'vue';

    export default {
        props: {
            shortname: {
                required: true
            },
            visible: {
                default: () => false
            }
        },

        watch: {
            visible: function (val) {
                console.log(val);
            }
        },

        mounted() {
            console.log(this.visible, this.shortname);
        },

        computed: {},

        methods: {}
    }

```

The result is, there is not result, it is not working. Maybe you could me some advice :)

**Comment by chrishurlburt** [comment]
Hi! thanks for taking the time to report this issue.

Is the list property on your home component being populated asynchronously?

**Comment by mapodev** [comment]
Yes it is. I'm loading data by AJAX.

**Comment by chrishurlburt** [comment]
Ok, I think I know what the issue is. The Scroll-view component is not able to detect a change in it's slot and react to it programmatically.

I am going to add a method to the $scrollview object that can be called on complete of an async operation to trigger <Scroll-view> to reasses it's slotted components and add begin tracking them properly.

I will get this deployed ASAP

**Comment by chrishurlburt** [comment]
I have added a .refresh() method to $scrollview that can be called to re-track components rendered after an async operation. Please update to v2.1.0

Use like this:

```js
ajax.get('https://example.com') // example ajax request/async operation
    .then(items => {
        this.list = items // set your list in state with the data returned
        Vue.nextTick(() => $scrollview.refresh()) // tell scrollview to update its tracking with newly rendered components
    })

```
Note the use of ```Vue.nextTick```. This is necessary so the components are rendered before scrollview attempts to track them.
