### ISSUE TITLE
More info on the scrollToComponent function

### ISSUE THREAD

**Issue by lindseybradford** [chrishurlburt/vue-scrollview#10]
Hi there, 

Great tool, thanks for building!

Do you have a recommended method for modifying the existing `scrollToComponent` function to implement a smooth scrolling animation? 

As a newbie, I'll inevitably use a duct-tape approach, and I wanted to see if there was a more elegant solution first.

Thanks!

**Comment by chrishurlburt** [comment]
Hi, thanks for using ScrollView!

For smooth scrolling, you can use a combination of `$scrollview.getComponentLocation('someKey')` and `window.scroll` with a scroll-behavior set. It would look something like this:

```js
const scrollLocation = $scrollview.getComponentLocation('someKey')
window.scroll({
  top: scrollLocation,
  left: 0,
  behavior: 'smooth'
})
```

Here's a pretty good article for explaining the `window.scroll` bit: [https://css-tricks.com/snippets/jquery/smooth-scrolling/](https://css-tricks.com/snippets/jquery/smooth-scrolling/)

Hopefully that accomplishes what you're looking for!
