### ISSUE TITLE
Is there any way to perform the inView scope only once?

### ISSUE THREAD

**Issue by michaelpumo** [chrishurlburt/vue-scrollview#2]
Just wondering if there is a way to stop watching a component if it's already been in view _once_?

I have a setup that adds a class to an element if it's in view, but then it also triggers the _removal_ of this class once it goes out of view again. Ideally I'd like to keep the class attached.

Typical setup is as shown in the docs:

```
<Scroll-View tag="div">
  <template scope="inView">
    <app-heading :visible="inView.heading1" key="heading1">Example</app-heading>
  </template>
</Scroll-View>
```

Thanks!

**Comment by chrishurlburt** [comment]
Hi, thanks for the question.

In your ```<app-heading>``` component, I assume you're binding the class based on the ```visible``` prop?

If so, i would create a watcher on the visible prop and set a piece of component state within ```<app-heading>``` that gets set to ```true``` when visible is ```true``` and use that to bind your class instead. This way, the class will be added as soon as the component becomes visible and never removed.

For example (in ```<app-heading>```):

```js
export default {
  data() {
    return {
      enteredViewport: false, // <- bind your class based on this
    }
  },
  watch: {
    visible(isVisible) {
      // enteredViewport remains true after the component enters
      // viewport for the first time.
      if (isVisible) this.enteredViewport = true
    }
  }
}
```

While this might not be a typical use case for watchers, I think it makes sense in this context.

Vue.js watchers: https://vuejs.org/v2/guide/computed.html#Watchers
